---
lsi         : false
pygments    : true
permalink   : none
markdown    : kramdown
baseurl     : http://www.scss.tcd.ie/~nallurv

kramdown:
    use_divs: true
    use_tex: true
    png_engine : blahtex
    png_dir    : images/latex/
    png_url    : /images/latex/

    
